### ISSUE TITLE
Showing duplicate entry when execute API first time

### ISSUE THREAD

**Issue by ruchitapatel1** [svkdprashant/Integrate-Authorize.net-API-PHP#1]
Hello,
API showing below error when I execute API in first time
 Array
(
    [success] => 0
    [customerProfileId] => 
    [customerPaymentProfileId] => 
    [error] => A duplicate record with ID 1505272091 already exists.
    [paymentFlag] => 0
    [message] => A duplicate record with ID 1505272091 already exists.
    [errorCode] => E00039
)

Also showing below error:
Array
(
    [success] => 0
    [customerProfileId] => 
    [customerPaymentProfileId] => 
    [error] => Root element is missing.
    [paymentFlag] => 0
    [message] => Root element is missing.
    [errorCode] => E00003
)

Can anyone help me?

**Comment by svkdprashant** [comment]
Hello,

Customer is already added into authorize.net account so API will not allow to add same customer again.
In this case, if you want to add new credit card/echeck for same customer then just pass the customer id "1505272091" (without quote) into API and it will add new credit card/echeck into authorize.net account.

Call like below and it will work:
$arrCustomerAddResponse = $objAuthorizeAPI->addCustomerPaymentProfile(111,'cc', true, 1505272091);

You can also check detail article on this here: http://code-bucket.co/how-to-integrate-authorize-net-api-with-php/

Let me know if you need any help

Thanks,
Prashant
